Dataset_dir: ./Dataset/hazelnut
Epochs: 100
batch_size: 64
device: cuda:0
encoded_space_dim: 128
img_size: 256
lr: 0.001
save_dir: MVtecAD
save_epoch: 99
seed: 42
target_class: 6
weight_decay: 1.0e-05
