Dataset_dir: ./Dataset/hazelnut
Decription: Normalize제외 하고 진행
Epochs: 50
aug_number: 3
batch_size: 32
device: cuda:0
encoded_space_dim: 256
img_size: 256
lr: 0.001
optimizer: adamw
save_dir: Gaus
seed: 42
target_class: 6
weight_decay: 1.0e-05
