Dataset_dir: ./Dataset/hazelnut
Decription: transformation resize-normalization 순서로 바꿔서 다시 진행
Epochs: 100
batch_size: 64
device: cuda:0
encoded_space_dim: 128
img_size: 256
lr: 0.001
optimizer: adamw
save_dir: MVtecAD2
seed: 42
target_class: 6
weight_decay: 1.0e-05
